### ISSUE TITLE
RawPostDataException when posting raw json

### ISSUE THREAD

**Issue by CallMeProteus** [earthcomfy/drf-phone-email-auth#1]
The inbuilt djangorestframework form posts to the route 'api/user/register' fine, however, when you switch to raw json, for example:

```
  {
    "password1": "root.@qw",
    "password2": "root.@qw",
    "phone_number": "+254........7"
}
```
something you would do from a client, a user is created but an exception is raised before the otp message is sent, tried httpie client and got a status code _201 but no OTP got dispatched. As it is, can only post from the django form.

**Comment by earthcomfy** [comment]
Hi @CallMeProteus What is the exception that got raised? If it is related to Twilio, you can go to http://localhost:8000/api/user/send-sms/ to get a new OTP (it might be a connection error).

**Comment by CallMeProteus** [comment]
> Hi @CallMeProteus What is the exception that got raised? If it is related to Twilio, you can go to http://localhost:8000/api/user/send-sms/ to get a new OTP (it might be a connection error).

'RawPostDataException' had misconfigurred my cors-headers,  got past that one though, http://localhost:8000/api/user/send-sms/  works as expected using raw json, it's on the http://localhost:8000/api/user/register/  that the issue is, it should send on an otp on resgistration as well using raw json,  otp only got sent when I used the framework's html form. 

seems like I'll have to use http://localhost:8000/api/user/send-sms/ till I find out why twilio is'nt resolving on registration on my end,  thanks @earthcomfy !!!

**Comment by CallMeProteus** [comment]
@earthcomfy  had my permissions set to isauthenticated, which once removed, everything worked like a charm, sorry, this is on me
